# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1471b873359717e1a421e61f8e15dd1c44a61c6811feedbf898a2a8cbdb8fc12ace359820820842582bdd5dbd31852d13115b40e750084aec0377b68c8cb06c5

test:
  secret_key_base: 6ac0af090819891d5d7c4e5532ea243210b11f0bff9431b7b387d5204aa7d19d12698a63961696c6fc959339799b5bbc5a91e8c6bf1513e7d9745b2b3f3f0976

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
